# config
spring:
  application:
    name: feign
  thymeleaf:
    cache: false


server:
  port: 8910

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
# feign自带熔断器,开启

# add notes
