# config
spring:
  application:
    name: feign
  thymeleaf:
    cache: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8950

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
# feign自带熔断器,开启

#add notes
